name: playlog_fix
description: Temporary scaffold for PlayLog with Firebase setup fixed.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  intl: ^0.20.2
  record: ^5.0.4
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  flutter_fft: ^1.0.2+6
  vibration: ^1.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_fft:
    path: packages/flutter_fft


flutter:
  uses-material-design: true
