name: playlog_fix
description: Temporary scaffold for PlayLog with Firebase setup fixed.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
